imports:
    - php

filter:
    paths: [src/*]

tools:
    external_code_coverage:
        enabled: true
        timeout: 1800
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]